server:
  port: 8080

spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/studentdb?serverTimezone=Australia/Sydney
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
com:
  student:
    learning:
      logging:
        level: debug,info
logging:
  file:
    name: /Users/adhikp/Downloads/StudentApp/src/main/resources/elk-stack.log
